version: '3.8'
services:
  
 cloud-weather-postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DATABASE=cloud_weather_percipitation_dev
      - POSTGRES_USER=cloud_weather_dev
      - POSTGRES_PASSWORD=cloud_weather_dev
    ports:
      - '5432:5432'
    volumes: 
      - postgres-data:/data/db

volumes:
    postgres-data:

